### ISSUE TITLE
Kicked for Outdated Client.

### ISSUE THREAD

**Issue by Ryah** [rom1504/rbot#41]
The error message was:
I got kicked for {"text":"Outdated client! Please use 1.11.2"} lol

I thought this was updated to 1.11.2?

**Comment by rom1504** [comment]
Did you run `npm install` ?

**Comment by Ryah** [comment]
(I'm running on Ubuntu 16.10)

I installed it with the way you showed in the readme (npm install -g rbot) and also tried cloning the git repo and running npm install on it. When I tried the second way, I didn't know how to start the bot correctly (tried running the rbot.js manually but came up with "SyntaxError: Unexpected token" . Reinstalling the first way (npm install -g rbot) just gave me the same error as the one in the OP.

**Comment by rom1504** [comment]
The second way is the correct way, I have published the updated version yet.
You can run rbot.js yes.
What version of node do you have ?
You need at least 6

**Comment by rom1504** [comment]
*haven't

**Comment by Ryah** [comment]
Just completely reinstalled nodejs to v6.9.4 (didn't realize Ubuntu's PPA was still only one v4), and got a new error. Here's the log from the terminal. I had to chmod the rbot.js file just for me to run it.

`You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
module.js:471
    throw err;
    ^

Error: Cannot find module 'mineflayer-blockfinder'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/unity/rbot/rbot.js:8:58)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

I apologize if it's me being stupid, I'm semi-new to all of this lol.

**Comment by Ryah** [comment]
Ok I was an idiot and didn't do npm install (I actually didn't have npm installed because it was removed with node, whoops). But now I get one more error. It seems like I'm able to join the server for a split second, but then I get this error.

```
I logged in.
settings { chat: 'enabled',
  colorsEnabled: true,
  viewDistance: 'far',
  difficulty: 2,
  showCape: true }
hello, Ryah! welmove to the server.
/home/unity/rbot/node_modules/prismarine-chunk/dist/pc/1.9/chunk.js:382
        throw e;
        ^

Error: Read error for skyLight : undefined
    at PartialReadError.ExtendableError (/home/unity/rbot/node_modules/protodef/dist/utils.js:105:11)
    at new PartialReadError (/home/unity/rbot/node_modules/protodef/dist/utils.js:118:91)
    at ProtoDef.readBuffer (/home/unity/rbot/node_modules/protodef/dist/datatypes/utils.js:174:45)
    at ProtoDef.read (/home/unity/rbot/node_modules/protodef/dist/protodef.js:102:31)
    at /home/unity/rbot/node_modules/protodef/dist/datatypes/structures.js:85:32
    at tryCatch (/home/unity/rbot/node_modules/protodef/dist/utils.js:83:12)
    at tryDoc (/home/unity/rbot/node_modules/protodef/dist/utils.js:90:10)
    at /home/unity/rbot/node_modules/protodef/dist/datatypes/structures.js:84:5
    at Array.forEach (native)
    at ProtoDef.readContainer (/home/unity/rbot/node_modules/protodef/dist/datatypes/structures.js:79:12)
```

**Comment by rom1504** [comment]
weird, what kind of server are you connecting to ?

**Comment by Ryah** [comment]
That error was on joining a CraftBukkit server 1.11.2. I thought it was Bukkit or a plugin messing with the server or something that the bot couldn't load, so I decided to try out a vanilla server and got this error instead.

```
I logged in.
settings { chat: 'enabled',
  colorsEnabled: true,
  viewDistance: 'far',
  difficulty: 2,
  showCape: true }
hello, Ryah! welmove to the server.

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: undefined == true
    at new Item (/home/unity/rbot/node_modules/prismarine-item/index.js:22:10)
    at Function.Item.fromNotch (/home/unity/rbot/node_modules/prismarine-item/index.js:61:10)
    at Client.<anonymous> (/home/unity/rbot/node_modules/mineflayer/lib/plugins/inventory.js:559:19)
    at emitTwo (events.js:106:13)
    at Client.emit (events.js:191:7)
    at Parser.<anonymous> (/home/unity/rbot/node_modules/minecraft-protocol/dist/client.js:101:16)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at readableAddChunk (/home/unity/rbot/node_modules/readable-stream/lib/_stream_readable.js:217:18)
    at Parser.Readable.push (/home/unity/rbot/node_modules/readable-stream/lib/_stream_readable.js:176:10)
    at Parser.Transform.push (/home/unity/rbot/node_modules/readable-stream/lib/_stream_transform.js:123:32)
```

Both of the servers are 1.11.2 servers.

**Comment by rom1504** [comment]
@Ryah did you eventually solve the problem somehow ?

**Comment by Ryah** [comment]
Yes. I'm not entirely sure why it wasn't working on the vanilla server, but I believe it had something to do with me being in the nether. Once I went to the overworld the bot was working fine.

There are some errors here and there that I have found, but I created an issue thread about those already.
