### ISSUE TITLE
TypeError: Cannot read property 'harvestTools' of undefined

### ISSUE THREAD

**Issue by mrminecart** [rom1504/rbot#50]
When using rbot and running any command which reuires to to dig, I get this message:

```
down
["taskList",[["taskList",[["exp",["tcc",[]]],["exp",["sbuild",[["position","r0,-2,0"]]]],["exp",["sdig",[["position","r0,-1,0"]]]],["exp",["wait",[["int","400"]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["tcc",[]]],["exp",["sbuild",[["position","r0,-2,0"]]]],["exp",["sdig",[["position","r0,-1,0"]]]],["exp",["wait",[["int","400"]]]]]]]]
I'm going to achieve task ["tcc",[]]
I achieved task ["tcc",[]]
["ifThen",[["condition",["is empty",[["position","r0,-2,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","r0,-2,0"]]]]]]]]]]]
I'm going to achieve task ["ifThen",[["condition",["is empty",[["position","r0,-2,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","r0,-2,0"]]]]]]]]]]]
I achieved task ["ifThen",[["condition",["is empty",[["position","r0,-2,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","r0,-2,0"]]]]]]]]]]]
["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r0,-1,0"]]]]]]]]],["condition",["is empty",[["position","r0,-1,0"]]]]]]
I'm going to achieve task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r0,-1,0"]]]]]]]]],["condition",["is empty",[["position","r0,-1,0"]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["ssdig",[["position","r0,-1,0"]]]]]]]]
["ifThen",[["condition",["is not empty",[["position","r0,-1,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","tool to break stone"]]]],["exp",["dig",[["position","r0,-1,0"]]]]]]]]]]]
I'm going to achieve task ["ifThen",[["condition",["is not empty",[["position","r0,-1,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","tool to break stone"]]]],["exp",["dig",[["position","r0,-1,0"]]]]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","tool to break stone"]]]],["exp",["dig",[["position","r0,-1,0"]]]]]]]]
I'm going to achieve task ["equip",[["destination","hand"],["item","tool to break stone"]]]
/home/woverton/Documents/CodingTest/minebot/rbot/lib/inventory.js:18
    var okTools = block.harvestTools;
                       ^

TypeError: Cannot read property 'harvestTools' of undefined
    at canHarvest (/home/woverton/Documents/CodingTest/minebot/rbot/lib/inventory.js:18:24)
    at Object.toolToBreak (/home/woverton/Documents/CodingTest/minebot/rbot/lib/inventory.js:31:7)
    at stringToItem (/home/woverton/Documents/CodingTest/minebot/rbot/lib/stringTo.js:146:76)
    at item (/home/woverton/Documents/CodingTest/minebot/rbot/lib/stringTo.js:21:38)
    at /home/woverton/Documents/CodingTest/minebot/rbot/lib/stringTo.js:39:119
    at /home/woverton/Documents/CodingTest/minebot/rbot/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/home/woverton/Documents/CodingTest/minebot/rbot/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/home/woverton/Documents/CodingTest/minebot/rbot/node_modules/async/lib/async.js:355:9)
    at Object.map (/home/woverton/Documents/CodingTest/minebot/rbot/node_modules/async/lib/async.js:337:20)
    at Object.stringTo (/home/woverton/Documents/CodingTest/minebot/rbot/lib/stringTo.js:39:8)

```

I am using spigot-1.11.2.jar

**Comment by rom1504** [comment]
fixed
