### ISSUE TITLE
Bot not responding or moving

### ISSUE THREAD

**Issue by monsterbear** [rom1504/rbot#54]
The bot Boots up fine and When it does It won't move can't even push it and won't respond to commands even setting master right When I kill it it responds in chat though Was doing the same thing with mineflayer?

**Comment by monsterbear** [comment]
Well For some reason he is now working ?

**Comment by monsterbear** [comment]
Okay so everything is working But It could be the server It works in single Is it possible to fix this? 


C:\Users\MonsterBear\Desktop\rbot-master\node_modules\minecraft-protocol\src\transforms\framing.js:76
          throw e;
          ^

Error: Deserialization error for play.toClient : Read error for name : 97 is not in the mappings value
    at ProtoDef.readMapper (C:\Users\MonsterBear\Desktop\rbot-master\node_modules\protodef\src\datatypes\utils.js:27:31)
    at ProtoDef.read (C:\Users\MonsterBear\Desktop\rbot-master\node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (C:\Users\MonsterBear\Desktop\rbot-master\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (C:\Users\MonsterBear\Desktop\rbot-master\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (C:\Users\MonsterBear\Desktop\rbot-master\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (C:\Users\MonsterBear\Desktop\rbot-master\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (<anonymous>)
    at ProtoDef.readContainer (C:\Users\MonsterBear\Desktop\rbot-master\node_modules\protodef\src\datatypes\structures.js:44:12)
    at ProtoDef.read (C:\Users\MonsterBear\Desktop\rbot-master\node_modules\protodef\src\protodef.js:39:25)
    at ProtoDef.read (C:\Users\MonsterBear\Desktop\rbot-master\node_modules\protodef\src\protodef.js:127:29)

**Comment by rom1504** [comment]
You need to use a supported version (see the readme), preferably with a
vanilla server (other servers might work but there probably is stuff to fix
for them)

**Comment by monsterbear** [comment]
Last question If the bot joins the server Why doesn't it respond to commands?

**Comment by monsterbear** [comment]
Its like No servers at all work with him

**Comment by rom1504** [comment]
It responds to in-chat commands. Are you doing that ?
In a vanilla server ?

**Comment by monsterbear** [comment]
I mean Vanilla Single player works Can It work on multi player servers? With some plugins

**Comment by monsterbear** [comment]
This is the server could test if you want http://cedarcraft.org/index.php/page/index.html

**Comment by monsterbear** [comment]
Thats the best I could find to vanilla

**Comment by rom1504** [comment]
I meant vanilla *server*
If you want to connect the bot to a spigot server with a chat plugin, you
probably need to parser the specific format for that plugin.
Look at mineflayer issues about chat, there are tons of people that dealt
with this issue before.

**Comment by rom1504** [comment]
To test on a vanilla server, you can just download one from Mojang site and
run it.

**Comment by monsterbear** [comment]
hmm Could you help me on that to get it working?

**Comment by monsterbear** [comment]
Could The chat plugins go with Rbot

**Comment by monsterbear** [comment]
https://github.com/PrismarineJS/mineflayer/tree/05337bce8724bb51511bd0ca11ce9f4782142ad5/lib/plugins/chat

**Comment by rom1504** [comment]
rbot depends on mineflayer so it already has everything mineflayer has.
Including that plugin.
But
every non-vanilla server implement its own chat format, so you need to
implement that format for your server, have a look at
https://github.com/PrismarineJS/mineflayer/issues?q=is%3Aissue+chat+is%3Aclosed

**Comment by rom1504** [comment]
fixed
